
/** identificacaoTransacao */
export interface IdentificacaoTransacao {
    /** dm_tipoTransacao|string|ENVIO_LOTE_GUIAS,ENVIO_ANEXO,SOLIC_DEMONSTRATIVO_RETORNO,SOLIC_STATUS_PROTOCOLO,SOLICITACAO_PROCEDIMENTOS,SOLICITA_STATUS_AUTORIZACAO,VERIFICA_ELEGIBILIDADE,CANCELA_GUIA,COMUNICACAO_BENEFICIARIO,RECURSO_GLOSA,SOLIC_STATUS_RECURSO_GLOSA,ENVIO_DOCUMENTO,PROTOCOLO_RECEBIMENTO,PROTOCOLO_RECEBIMENTO_ANEXO,RECEBIMENTO_RECURSO_GLOSA,DEMONSTRATIVO_ANALISE_CONTA,DEMONSTRATIVO_PAGAMENTO,DEMONSTRATIVO_ODONTOLOGIA,SITUACAO_PROTOCOLO,RESPOSTA_SOLICITACAO,AUTORIZACAO_ODONTOLOGIA,STATUS_AUTORIZACAO,SITUACAO_ELEGIBILIDADE,CANCELAMENTO_GUIA_RECIBO,RECIBO_COMUNICACAO,RESPOSTA_RECURSO_GLOSA,RECEBIMENTO_DOCUMENTO */
    tipoTransacao?: string;
    /** st_texto12|string|minLength,maxLength */
    sequencialTransacao?: string;
    /** st_data|date */
    dataRegistroTransacao?: string;
    /** st_hora|time */
    horaRegistroTransacao?: string;
}
